version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-gym-bro-app
    cap_add:
      - NET_ADMIN
    volumes:
      - .:/app
    env_file:
      - .env
    # Ensure that init.sh is present in the image or mounted as a volume.
    user: "root"
    command: ["/bin/sh", "-c", "chmod +x proxy-init.sh && ./proxy-init.sh && poetry install && poetry run run-bot"]
    network_mode: "service:proxy"

  proxy:
    build:
      context: .
      dockerfile: Dockerfile.proxy
      secrets:
        - proxy_creds
    container_name: ai-gym-bro-proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "12345:12345"
    volumes:
      - ./proxy-init.sh:/init.sh
    env_file:
      - .env
    # The proxy container uses the same init script logic then starts redsocks.
    command: ["/bin/sh", "-c", "chmod +x /init.sh && /init.sh && exec redsocks -c /etc/redsocks.conf"]

secrets:
  proxy_creds:
    file: ./proxy.creds
